name: PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  merge_group:
    types: [checks_requested]

jobs:
  verify_title:
    name: Verify Title
    runs-on: ubuntu-latest
    if: ${{github.event.action != 'checks_requested'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install Packages
        run: npm ci
      - name: Run Commitlint
        run: echo "${{github.event.pull_request.title}}" | npx commitlint
