name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    if: github.repository == '@ydb-platform/monaco-yql-languages'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          token: ${{ secrets.YDB_PLATFORM_BOT_TOKEN_REPO }}
          release-type: node
